# Generated by Django 5.2 on 2025-05-05 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_remove_valor_producto_rename_valor_producto_precio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimiento',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='descripcion',
        ),
    ]
